# Generated by Django 4.1.5 on 2023-01-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_auto_20221109_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='aksesoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=30)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jenis_prabot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=30)),
                ('ket', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='perabotan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=30)),
                ('harga', models.BigIntegerField()),
                ('deskrip', models.CharField(max_length=100)),
                ('jenis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.jenis_prabot')),
            ],
        ),
    ]
